# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Fri, 22 May 2020 13:42:43 +0000
*               @ALL          1
*               @user         8
